### ISSUE TITLE
Can't import pebble in python3

### ISSUE THREAD

**Issue by jbinas** [obilaniu/CodeSnips#1]
https://github.com/obilaniu/CodeSnips/blob/a406d459463578c624fb298510a512f11c88677a/python/pysnips/ml/tfevents.py#L12

To make it work in python3, this needs to be

`from   .pebble              import (PebbleMessage, `

**Comment by obilaniu** [comment]
As asked by at least two other people, I moved out the code in question to a separate repo:
_Zvit_ (https://github.com/obilaniu/Zvit)

That code base is Python-3-only and -clean. It's also a package on PyPI that can be installed with `pip install zvit`.

I forgot to delete this part of the CodeSnips repository, and you should definitely not use it.

**Comment by jbinas** [comment]
I see, thanks!
